### ISSUE TITLE
Créer une campagne – Info perdu.

### ISSUE THREAD

**Issue by massiwen** [gti525/h19-analytique#86]
La validation des informations fait tout disparaitre quand le bouton Enregistrer est cliqué.
Voire image.
![creatCamp](https://user-images.githubusercontent.com/11389343/54059418-1948a780-41c7-11e9-93bc-41c105542e4f.png)

**Comment by sanibelle** [comment]
Normal, il faudrait faire la validation aussi au front mais ce n'est pas demandé alors on perd tout :)
