### ISSUE TITLE
Créer une campagne – Stack d’erreurs

### ISSUE THREAD

**Issue by massiwen** [gti525/h19-analytique#88]
Quand je créer une campagne, j’ai une stack d’erreurs
Voire image
![creatCampErr](https://user-images.githubusercontent.com/11389343/54059642-dd621200-41c7-11e9-81e3-1f1f3b9ccc44.png)

**Comment by sanibelle** [comment]
J'avais résolu ce bug normallement.  Ça a peu d'incidence normalement.  As-tu la dernière branche mise à jour? git pull origin dev?

**Comment by massiwen** [comment]
Je suis sur le master car: 	Git Pull Failed
			From https://github.com/gti525/h19-analytique
			* branch            dev        -> FETCH_HEAD
			cannot lock ref 'refs/remotes/origin/dev': is at 2e60b76ad92309bbad9f5d1d925f1d0a4e814101 but expected 546ce8a36cf6f625911179bbbe2500217a084425
			! 546ce8a..c5e570d  dev        -> origin/dev  (unable to update local ref)
