### ISSUE TITLE
Créer profile – Validation id

### ISSUE THREAD

**Issue by massiwen** [gti525/h19-analytique#89]
Deux profiles avec le même id peuvent être créés.
Voire image.
![creerProfileDuplicateId](https://user-images.githubusercontent.com/11389343/54059738-30d46000-41c8-11e9-9b8a-5a1efe07a8e6.png)

**Comment by sanibelle** [comment]
Hmmmm ce n'est pas tant un bug...... C'est l'identifiant en texte et non pas ce qui est dans la bd.  Disons que c'est correct
