### ISSUE TITLE
Modifier profile – fonctionne pas

### ISSUE THREAD

**Issue by massiwen** [gti525/h19-analytique#91]
Cliquer sur l’icône de modification ne permet pas de modifier le profile.
Voire image.
![profileEdit](https://user-images.githubusercontent.com/11389343/54059898-c7a11c80-41c8-11e9-8d90-645d12ad1470.png)

**Comment by sarkmi15** [comment]
Ça marche de mon bord, je suis sur dev 
![bug_peut_pas_modifier_profile](https://user-images.githubusercontent.com/14181002/54065569-b8ce6000-41f0-11e9-89ba-f92908b1c9c5.png)
