### ISSUE TITLE
Récupérer ses revenus – fonctionne pas

### ISSUE THREAD

**Issue by massiwen** [gti525/h19-analytique#92]
Cliquer sur le bouton (Récupérer ses revenus) ouvre une page d’erreurs.
Voire image.
![RecupererRevenu](https://user-images.githubusercontent.com/11389343/54059986-0fc03f00-41c9-11e9-9674-81e5f1cc268a.png)

**Comment by sarkmi15** [comment]
J'ai trouvé que quand j'appuie sur récupérer ses revenus, ¸ la page ne change pas ça reste sur /income, ça passe pas à /income/transfer

**Comment by Edoz77** [comment]
> 
> 
> J'ai trouvé que quand j'appuie sur récupérer ses revenus, ¸ la page ne change pas ça reste sur /income, ça passe pas à /income/transfer

C'est normal.

**Comment by sarkmi15** [comment]
Cool je vais fermer le bogue :)
