### ISSUE TITLE
Créer profile – Texte en anglais

### ISSUE THREAD

**Issue by massiwen** [gti525/h19-analytique#93]
Cliquer sur le bouton (Enregistrer) avec du texte dans le mauvais format affiche un message en anglais et pas en français.
Voire image.
![creatProfile](https://user-images.githubusercontent.com/11389343/54060034-3c745680-41c9-11e9-894f-22cd5ed0a9bb.png)

**Comment by sarkmi15** [comment]
Ça à l'air bon de mon bord, je vais le mettre sur done


![bug_respecte_pas_format](https://user-images.githubusercontent.com/14181002/54065483-9ab43000-41ef-11e9-8379-3d49d8648079.png)
